name: Test head command

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $COMMIT_MESSAGE | head -1
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
