name: Test head command

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set header of commit message as env variable
        run: |
          COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B | head -1)
          echo "COMMIT_MESSAGE_HEADER=${COMMIT_MESSAGE_HEADER}" >> $GITHUB_ENV
