name: Build and deploy

on:
  push:
    branches:
    - master
    paths-ignore:
    - .gitignore
    - LICENSE
    - README.md
    - images/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build
    - run: npm i -g firebase-tools
    - run: echo ::set-env name=COMMIT_MESSAGE_FIRST_LINE::"$(echo '${{ github.event.head_commit.message }}' | head -1)"
    - run: firebase deploy -m "$COMMIT_MESSAGE_FIRST_LINE" --token "$FIREBASE_TOKEN"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}