name: Build and deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - images/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      - run: npm ci
      - run: npm run build
      - run: npm i -g firebase-tools
      - name: Set header of commit message as env variable
        run: |
          COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B | head -1)
          echo "COMMIT_MESSAGE_HEADER=${COMMIT_MESSAGE_HEADER}" >> $GITHUB_ENV
      - run: firebase deploy -m $COMMIT_MESSAGE_HEADER
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
